
POST http://localhost:3000/clients HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@j.com"
}

###

POST http://localhost:3000/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "87495b95-1c7f-4038-ae55-ab36ed6a9411"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "b8851416-a486-465f-bc14-00dd2eab30c9",
    "account_id_to": "91c61fd4-0e44-4bda-9b7e-1a4083c019ea",
    "amount": 1
}
