services:
  balance_app:
    build: .
    depends_on:
      balances_db:
        condition: service_healthy
    ports:
      - "8082:8080"
    environment:
      KAFKA__BootstrapServers: kafka:29092
      KAFKA__Topic: balances
      KAFKA__GroupId: wallet
  balances_db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wallet 
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - .docker/balances_db:/var/lib/mysql
      - ./migrations/01. CREATE schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./migrations/02. INSERT balances.sql:/docker-entrypoint-initdb.d/2.sql
    healthcheck:
      test: [ 
        "CMD-SHELL",
        "mysql -uroot -proot -e 'use wallet;'"
      ]
      interval: 5s
      timeout: 10s
      retries: 3
